### ISSUE TITLE
CMake version

### ISSUE THREAD

**Issue by egcpvanloon** [krivenko/pomerol2triqs#10]
When using CMAKE_CXX_STANDARD 17, I think 3.8 is the minimum required version of cmake. There were some commits along these lines at some point, but they were reverted again, and the CXX_STANDARD was increased later leading to an inconsistency. This is what CMakeLists.txt currently looks like:

# Start configuration
cmake_minimum_required(VERSION 3.**1** FATAL_ERROR)
project(pomerol2triqs CXX)
set(CMAKE_CXX_STANDARD 17)

Best,

Erik

**Comment by krivenko** [comment]
Hi Erik,

Are you okay with requiring CMake 3.8 or newer? (https://github.com/krivenko/pomerol2triqs/pull/11).

Best regards,
Igor

**Comment by egcpvanloon** [comment]
Yes, that should work.
