### ISSUE TITLE
Triqs 2.2 compatibility

### ISSUE THREAD

**Issue by egcpvanloon** [krivenko/pomerol2triqs#12]
Hi,

Is pomerol2triqs compatible with triqs 2.2? I am having some issues compiling it. For example, triqs/mpi/boost.hpp no longer exists in triqs 2.2.

Best,

Erik

**Comment by krivenko** [comment]
Hi Erik,

If there is a missing header, then `pomerol2triqs` is obviously incompatible with the latest version of the library. I am currently on vacation, would need a few days to test my application against TRIQS 2.2 and see what needs to be done to restore compatibility.

Igor

**Comment by egcpvanloon** [comment]
Hi Igor,

I found some changes that fixed the problem (at least for me):
https://github.com/lyuwen/triqs-pomerol-docker/blob/master/pomerol2triqs.patch

Erik

**Comment by krivenko** [comment]
Hi Erik,

I have finally found some time to look into this issue. @lyuwen's patch does make the code compile with TRIQS 2.2, although I am getting a segmentation fault in the `slater_gf` unit test now. Might have something to do with https://github.com/TRIQS/triqs/pull/559.

Igor

**Comment by lyuwen** [comment]
Hey guys, 

I just checked my docker image and the tests passed just fine. Not sure why you would have such problem though.

Lyuwen
