### ISSUE TITLE
does the bath-parameters affect the results? 

### ISSUE THREAD

**Issue by abdelghany0** [krivenko/pomerol2triqs#19]
Hi, 

May I know on what basis the values of the bath parameters (epsilon and V) are chosen? 

```
# Levels of the bath sites
epsilon = [-1.0, 1.0]
# Hopping amplitudes
V = [0.5, 0.5]
```
Are these parameters optimized during the calculations or not?

Another inequality please:
Is there an available tutorial for using pomerol2triqs with DMFT calculations? 

Best, 
Ragab.

**Comment by krivenko** [comment]
Hello,

>  Is there an available tutorial for using pomerol2triqs with DMFT calculations?

No, none I am aware of.

`pomerol2triqs` was written to provide reference data to test other, more versitile solvers (mainly QMC).
Perhaps the only case where it was used to do an actual DMFT calculation is this work by Erik van Loon,

Erik G C P van Loon 2021 J. Phys.: Condens. Matter 33 135601
https://iopscience.iop.org/article/10.1088/1361-648X/abd9ed
 https://arxiv.org/abs/2011.08780.

> May I know on what basis the values of the bath parameters (epsilon and V) are chosen?
> 
> epsilon = [-1.0, 1.0]
> V = [0.5, 0.5]
> 
> Are these parameters optimized during the calculations or not?

You would need to somehow optimize these parameters during a real DMFT calculation.
I my example scripts, however, they are just some illustrative input data chosen mostly randomly.

**Comment by abdelghany0** [comment]
I see, Thank you!

**Comment by krivenko** [comment]
Since your questions are answered, can I close this issue now?

**Comment by abdelghany0** [comment]
Yes, please!
