### ISSUE TITLE
PP Two-particle Green's function has the zeroth Bosonic frequency shifted by one?!

### ISSUE THREAD

**Issue by HugoStrand** [krivenko/pomerol2triqs#2]
Dear Igor,

I have spotted an oddity in the PP-channel two particle Green's function, when benchmarking `triqs/cthyb`. When asking for 15x15x15 frequencies the shape of both the PP and PH gfs are:

```
gpp.data.shape == (29, 30, 30, 1, 1, 1, 1)
```
However the zeroth bosonic frequency (the first index) is located at index 13 for the PP-gf and at index 14 for the PH-gf. Please see the `triqs/cthyb` benchmark and the PP channel comparison and compare with the PH case:

https://github.com/TRIQS/cthyb/blob/dev_measures/benchmark/measure_g2/hubbard_atom_2bath/CompareEDandCTHYB.ipynb

Is this frequency shift intended or a bug? Or have I messed something up?

Best regards,
Hugo

**Comment by krivenko** [comment]
Hi Hugo,

Yes, this is a bug, and I already have a fix for it.
I'll push it as soon as I'm done with testing.

Regards,
Igor

**Comment by HugoStrand** [comment]
Dear Igor,

Thank you for the rapid reply. Please let me know when you are done and I'll repeat the cthyb tests.

Cheers, Hugo
