### ISSUE TITLE
Is there an option for an additional symmetry check?

### ISSUE THREAD

**Issue by j-otsuki** [krivenko/pomerol2triqs#3]
Dear Igor,

At present, only Sz is used for state classification as in the default mode of pomerol.  In the Slater Hamiltonian, for example, Lz (w/o SO) or Jz (w/ SO) could be additionally used to reduce the block size.

Is there any way to pass an Operator op to call symm.checkSymmetry(op)? Or, if not, which is the easiest way to extend the code?

It seems for me that one should extend the function pomerol_ed::diagonalize to be able to pass a list of operators that is used for additional symmetry check.

Best regards,
Junya

**Comment by krivenko** [comment]
Dear Junya,

The feature you are asking for has to be implemented on the level of Pomerol. Exposing it in pomerol2triqs would then be trivial. Let me copy this issue to the repository of Pomerol.

Best regards,
Igor

**Comment by krivenko** [comment]
@j-otsuki 
Here you go: https://github.com/aeantipov/pomerol/issues/10

**Comment by j-otsuki** [comment]
@krivenko 
thank you, Igor, for your response.

I found the following descriptions in the pomerol tutorial, example2site.cpp:
```
    // Construct Symmetrizer
    Symmetrizer Symm(IndexInfo, Storage);
    /* At this stage Symmetrizer checks symmetries with some predefined operators,
     * such as number-of-particles and sz operators.
     */
    Symm.compute();
    /* A custom check for a symmetry can be done using
     * Symmetrizer.checkSymmetry(Operator).
     * After checking all the symmetry operations, Symmetrizer defines a set of
     * quantum numbers, which uniquely identifies the closed region in the
     * phase space.
     * Calling Symmetrizer::compute(true) will skip all symmetry operations and
     * result in a single Hamiltonian block in the end.
     */
```

So, maybe we define `Operator Lz` in triqs, pass it to pomerol2triqs in some way, and then do
```
Symmetrizer Symm(IndexInfo, Storage);
Symm.checkSymmetry(Lz);
Symm.compute();
```
Does it work?

**Comment by krivenko** [comment]
> Does it work?

Well, this might work, albeit I don't remember anyone testing it.
Moreover, even if it works, I'd suggest changing (extending) the API so that there is no need to call `checkSymmetry()` explicitly.

**Comment by j-otsuki** [comment]
>Well, this might work, albeit I don't remember anyone testing it.

Okay, I could add some lines to call checkSymmetry(op) in pomerol2triqs.
Testing is no problem. I will compare results with and without chenkSymmetry().

>Moreover, even if it works, I'd suggest changing (extending) the API so that there is no need to call checkSymmetry() explicitly.

Is that mean that we perform something like
```
for op in possible_operators:
    checkSymmetry(op)
```
inside the pomerol solver, so that there is no need to call checkSymmetry() explicitly?
Or, we could do that in pomerol2triqs instead.
In any case, such an extension is very nice.

Best,
Junya

**Comment by krivenko** [comment]
> Is that mean that we perform something like
> 
> for op in possible_operators:
>     checkSymmetry(op)
> 
> inside the pomerol solver, so that there is no need to call checkSymmetry() explicitly?
> Or, we could do that in pomerol2triqs instead.

I think we should change Pomerol's code, and add an overload of `Symmetrizer::compute()` that takes `std::vector<Operator>`.
