### ISSUE TITLE
Static expectation values?

### ISSUE THREAD

**Issue by HugoStrand** [krivenko/pomerol2triqs#4]
Dear Igor,

I have looked through the example scripts but I can not find any example on how got compute static expectation values. Is there such functionality? or do I have to take the `\beta=0` limit of a single-particle Green's function.

Cheers, Hugo

**Comment by krivenko** [comment]
Dear Hugo,

pomerol2triqs does not feature computation of static observables, because pomerol cannot compute them. If you only need the occupation numbers, then taking `1+G(\tau=0)` is the only satisfactory solution (set `n_tau=2` to speed up computation). 

Igor

**Comment by HugoStrand** [comment]
Dear Igor,

Thank you for the rapid response. Ok, too bad, I was hoping to compute some slightly more complicated operator expressions. Then I'll use `pyed` (https://github.com/HugoStrand/pyed) for that.

Cheers, Hugo
